sudo: false
language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"

before_install:
   - pip install pytest-cov
   - pip install pytest-mpl

install: "pip install -r requirements.txt"

script: py.test --mpl-generate-path=generated --cov striplog tests

after_success:
   - coveralls
